[features]
seeds = false
[programs.devnet]
ordering_system = "3JFgCsPEVh7RUy4PP1kN6ittyXuXNsxRWcY25BmncgAn"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/guardian/work/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
